### ISSUE TITLE
http://client:secret@localhost:9000/oauth/token 这步的postman操作流程能不能具体点呢?

### ISSUE THREAD

**Issue by hzhh110** [heartsuit/demo-springboot-oauth2#1]
通过授权码向授权服务获取令牌：access_token

http://client:secret@localhost:9000/oauth/token

将上一步获取的授权码作为x-www-form-urlencoded的一个参数：

grant_type:authorization_code code:wgs8XF

**Comment by heartsuit** [comment]
![图片](https://user-images.githubusercontent.com/8071981/109450487-f4216380-7a85-11eb-85be-11592cc497e2.png)
